### ISSUE TITLE
mkfs.bfs does not create valid filesystems if compiled for 64bit or on machines with other endianes.

### ISSUE THREAD

**Issue by ihno** [util-linux/util-linux#34] opened 2013-06-07 17:09 UTC
The code is not 64-bit or endian clean.

**Comment by mator** [comment] 2022-03-31 11:11
I can't reproduce on a sparc64 (BE, 8K pagesize) linux with git version of util-linux, `mkfs.bfs` compiles without errors, creates fs, put test file ok, unmount/mount and reading test file ok.

```
util-linux# fallocate -l 100M ./bfs-test1.bin
util-linux# losetup -f --show ./bfs-test1.bin
/dev/loop0
util-linux# ./mkfs.bfs /dev/loop0
util-linux# mount /dev/loop0 -t bfs /mnt
util-linux# echo hello > /mnt/test.txt
util-linux# cat /mnt/test.txt
hello
util-linux# umount /mnt
util-linux# mount /dev/loop0 -t bfs /mnt
util-linux# cat /mnt/test.txt
hello
util-linux# umount /mnt
```
kernel log:
```
util-linux# journalctl -k -e
Mar 31 14:01:28 ttip kernel: loop0: detected capacity change from 0 to 204800
Mar 31 14:01:44 ttip kernel: BFS-fs: bfs_fill_super(): NOTE: filesystem loop0 was created with 512 inodes, the real maximum is 511, mounting anyway
Mar 31 14:02:09 ttip kernel: BFS-fs: bfs_fill_super(): NOTE: filesystem loop0 was created with 512 inodes, the real maximum is 511, mounting anyway
```

Lets close this issue or provide more details?

**Comment by karelzak** [comment] 2022-04-01 07:37
Closing ...

**Closed by karelzak** 2022-04-01 07:37 UTC
