### ISSUE TITLE
Failure to mount zram-backed XFS with v2.39; thinks filesystem is ext4

### ISSUE THREAD

**Issue by jlebon** [util-linux/util-linux#2161] opened 2023-04-11 19:30 UTC
As directed at https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/LPC3UNO6ECFIOGAEX4BZRFFTRK5Q5J7S/, this is an issue to track a new failure we've observed with v2.39: https://github.com/coreos/fedora-coreos-tracker/issues/1462

This is happening when trying to mount an XFS-formatted zram device. It seems like specifying the type when mounting works around this: https://github.com/coreos/fedora-coreos-config/pull/2362. Attached is the output with `LIBMOUNT_DEBUG=all` without the workaround.

[zram-output.txt](https://github.com/util-linux/util-linux/files/11204201/zram-output.txt)

**Comment by karelzak** [comment] 2023-04-12 07:08
It would be nice to get also output from LIBBLKID_DEBUG=all. It does seem related to the new mount API, but as an issue with FS detection (for example, the late XFS prober in libblkid check FS checksum).

Do you have the Zram image somewhere to download? Or how can I reproduce it? 

Thanks for your report.

**Comment by karelzak** [comment] 2023-04-12 10:04
I see the script at https://github.com/coreos/fedora-coreos-config/pull/2362/commits/6d08429a6f9d7492e3da26304c6a2c9a8bc189f4; I'll try to reproduce it locally.

**Comment by karelzak** [comment] 2023-04-12 10:31
It works for me; here is the script (copy & past from your test suite):

```shell
#!/bin/bash                                                        
      
saved_data="/mnt/test"                                             
      
set -x
      
mem_available=$(grep MemAvailable /proc/meminfo | awk '{print $2}')
if [ "${mem_available}" -lt $((1*1024*1024)) ] && [ "${wipes_root}" != 0 ]; then 
echo "Root reprovisioning requires at least 3G of RAM" >&2
exit 1
fi    
modprobe zram num_devices=0
read dev < /sys/class/zram-control/hot_add
echo 10G > /sys/block/zram"${dev}"/disksize
echo $(( mem_available * 90 / 100 ))K > /sys/block/zram"${dev}"/mem_limit
mkfs.xfs -q /dev/zram"${dev}"
mkdir -p "${saved_data}"
      
./mount /dev/zram"${dev}" "${saved_data}"
      
fstype=$(findmnt /mnt/test -no FSTYPE)
if [ "$fstype" != "xfs" ]; then
    echo "no XFS mounted on ${saved_data}"
    exit 1
fi    
umount ${saved_data}
rmmod zram

```

What I see as problematic in your test is missing `udevadm settle` after mkfs.xfs. It's possible that libblkid accesses the device in time when it's not ready yet. In the test is always a good idea to use udevadm settle after mkfs or fdisk/parted.

**Comment by karelzak** [comment] 2023-04-12 10:32
I get:
```
# ../tools/zram-xfs.sh
++ grep MemAvailable /proc/meminfo
++ awk '{print $2}'
+ mem_available=7588876
+ '[' 7588876 -lt 1048576 ']'
+ modprobe zram num_devices=0
+ read dev
+ echo 10G
+ echo 6829988K
+ mkfs.xfs -q /dev/zram0
+ mkdir -p /mnt/test
+ ./mount /dev/zram0 /mnt/test
++ findmnt /mnt/test -no FSTYPE
+ fstype=xfs
+ '[' xfs '!=' xfs ']'
+ umount /mnt/test
+ rmmod zram
```

**Comment by jlebon** [comment] 2023-04-17 19:19
> It would be nice to get also output from `LIBBLKID_DEBUG=all`.

I've attached the new output with both `LIBMOUNT_DEBUG=all` and `LIBBLKID_DEBUG=all` defined. Apologies, I didn't clean it as well as the first time so there's some output from systemd and other services interspersed.

[zram-output.txt](https://github.com/util-linux/util-linux/files/11254798/zram-output.txt)

> Do you have the Zram image somewhere to download? Or how can I reproduce it?
> It works for me; here is the script (copy & past from your test suite):

Hmm, not sure why your test script isn't reproducing it. Wonder if it somehow has to do with the fact that this all happens in the initramfs.

Reproducing this the same way we do is a bit tricky. The easiest would probably be to build FCOS rawhide yourself, which isn't hard but takes some work if you're not familiar with our build tooling. I could upload a qcow2 with the latest util-linux, but you'll probably want to have custom builds with different util-linux versions. Let me know if you want me to provide instructions for this.

> What I see as problematic in your test is missing `udevadm settle` after mkfs.xfs. It's possible that libblkid accesses the device in time when it's not ready yet. In the test is always a good idea to use udevadm settle after mkfs or fdisk/parted.

Good point. Do you think this is still necessary if we directly specify the filesystem type like in https://github.com/coreos/fedora-coreos-config/commit/e018c684bd44a56255ee9420fbffd39af7712661?

**Comment by t-8ch** [comment] 2023-04-18 07:29
The ext4 warning is from *before* the blkid probing, so it should be unrelated.
```
[    2.736636] EXT4-fs (zram0): VFS: Can't find ext4 filesystem
```
xfs blocksize is 4096 and the xfs checksum validation fails.
```
[    2.874928] ignition-ostree-transposefs[742]: 742: libblkid: LOWPROBE: 	read: off=0 len=4096
[    2.875319] ignition-ostree-transposefs[742]: incorrect checksum for type xfs, got A3515B9600000000, expected 3ADFB7E200000000
```
*No* filesystem is detected.
```
[    3.033656] ignition-ostree-transposefs[742]: 742: libmount:      CXT: [0x561e710fdbd0]: FS type: (null) [rc=0]
```

This should indeed be the same as #2165.

**Comment by karelzak** [comment] 2023-04-18 12:05
I guess we can close this one.

**Comment by karelzak** [comment] 2023-04-18 14:18
I will release -rc3 (due to some changes in libmount) and push it to Fedora tomorrow or on Thu. It will be with the bugfix.

**Comment by jlebon** [comment] 2023-04-18 16:23
I can confirm the latest `master` tree fixes this issue and another issue I was about to file related to 4K native disks (I see https://github.com/util-linux/util-linux/pull/2165 mentions this so I presume it also fixed that).

> I will release -rc3 (due to some changes in libmount) and push it to Fedora tomorrow or on Thu. It will be with the bugfix.

Thanks!

**Closed** 2023-04-20 05:42 UTC
