### ISSUE TITLE
lsfd: mkfds-multiplexing-{pselect6,poll,ppoll} fail on MIPS64

### ISSUE THREAD

**Issue by xry111** [util-linux/util-linux#2867] opened 2024-03-27 21:55 UTC
```
diff-{{{
--- /home/xry111/sources/lfs/util-linux-2.40/tests/expected/lsfd/mkfds-multiplexing-pselect6	2024-03-20 22:32:18.160554638 +0800
+++ /home/xry111/sources/lfs/util-linux-2.40/tests/output/lsfd/mkfds-multiplexing-pselect6	2024-03-28 05:51:54.632940479 +0800
@@ -1,13 +1,14 @@
-10 r----m
+10 r-----
 11 -w----
-12 -w---m
+12 -w----
 13 r-----
-14 r----m
+14 r-----
 15 -w----
-16 r----m
+16 r-----
 17 -w----
-18 -w---m
+18 -w----
 19 r-----
-20 r----m
+20 r-----
 21 -w----
 [pselect6] ASSOC,XMODE: 0
+0 0x15 0xfffbdf1eb8 0xfffbdf1e38 0xfffbdf1db8 0x0 0xfffbdf1d38 0xfffbdf1d28 0xfff044c9e0
}}}-diff
```

It looks like `/proc/${pid}/syscall` is completely broken on MIPS.  I tried running `./test_mkfds -w poll multiplexing {10..22}` manually and its `/proc/${pid}/syscall` is:

```
0 0xaacefc46b0 0x7 0xffffffffffffffff 0xfffbd105c0 0xfff0883e68 0xfff08417f4 0xfffbd10678 0xfff074c9e0
```

Hmm, so it looks like the syscall number is in the third field but I cannot find nfds at all.

Not sure what we should do.  Maybe just marking these tests XFAIL on MIPS?

**Comment by xry111** [comment] 2024-03-27 22:04
@FlyGoat or do you have some idea about fixing this on the kernel side?

**Comment by FlyGoat** [comment] 2024-03-28 11:05
@xry111 I think the problem is our hand crafted partial save syscall handling routines (i.e. `scall64-n64.S` stuff) is not saving all the stuff to `pt_regs` at the entrance.

Will try to come up a fix.

**Comment by FlyGoat** [comment] 2024-03-28 11:38
Hi @xry111,

Do you fancy to test following kernel patch? (based on linux-next)

```
diff --git a/arch/mips/kernel/asm-offsets.c b/arch/mips/kernel/asm-offsets.c
index d1b11f66f748..cb1045ebab06 100644
--- a/arch/mips/kernel/asm-offsets.c
+++ b/arch/mips/kernel/asm-offsets.c
@@ -101,6 +101,7 @@ void output_thread_info_defines(void)
 	OFFSET(TI_CPU, thread_info, cpu);
 	OFFSET(TI_PRE_COUNT, thread_info, preempt_count);
 	OFFSET(TI_REGS, thread_info, regs);
+	OFFSET(TI_SYSCALL, thread_info, syscall);
 	DEFINE(_THREAD_SIZE, THREAD_SIZE);
 	DEFINE(_THREAD_MASK, THREAD_MASK);
 	DEFINE(_IRQ_STACK_SIZE, IRQ_STACK_SIZE);
diff --git a/arch/mips/kernel/scall32-o32.S b/arch/mips/kernel/scall32-o32.S
index 18dc9b345056..66b06b73664d 100644
--- a/arch/mips/kernel/scall32-o32.S
+++ b/arch/mips/kernel/scall32-o32.S
@@ -77,6 +77,8 @@ loads_done:
 	PTR_WD	load_a7, bad_stack_a7
 	.previous
 
+	LONG_S	v0, TI_SYSCALL($28)     # Store syscall number
+
 	lw	t0, TI_FLAGS($28)	# syscall tracing enabled?
 	li	t1, _TIF_WORK_SYSCALL_ENTRY
 	and	t0, t1
diff --git a/arch/mips/kernel/scall64-n32.S b/arch/mips/kernel/scall64-n32.S
index 97456b2ca7dc..f20cb1f01f54 100644
--- a/arch/mips/kernel/scall64-n32.S
+++ b/arch/mips/kernel/scall64-n32.S
@@ -44,6 +44,8 @@ NESTED(handle_sysn32, PT_SIZE, sp)
 
 	sd	a3, PT_R26(sp)		# save a3 for syscall restarting
 
+	LONG_S	v0, TI_SYSCALL($28)     # Store syscall number
+
 	li	t1, _TIF_WORK_SYSCALL_ENTRY
 	LONG_L	t0, TI_FLAGS($28)	# syscall tracing enabled?
 	and	t0, t1, t0
diff --git a/arch/mips/kernel/scall64-n64.S b/arch/mips/kernel/scall64-n64.S
index e6264aa62e45..3c1d708d5c09 100644
--- a/arch/mips/kernel/scall64-n64.S
+++ b/arch/mips/kernel/scall64-n64.S
@@ -46,6 +46,8 @@ NESTED(handle_sys64, PT_SIZE, sp)
 
 	sd	a3, PT_R26(sp)		# save a3 for syscall restarting
 
+	LONG_S	v0, TI_SYSCALL($28)     # Store syscall number
+
 	li	t1, _TIF_WORK_SYSCALL_ENTRY
 	LONG_L	t0, TI_FLAGS($28)	# syscall tracing enabled?
 	and	t0, t1, t0
diff --git a/arch/mips/kernel/scall64-o32.S b/arch/mips/kernel/scall64-o32.S
index d3c2616cba22..900f2f45ff7b 100644
--- a/arch/mips/kernel/scall64-o32.S
+++ b/arch/mips/kernel/scall64-o32.S
@@ -33,6 +33,8 @@ NESTED(handle_sys, PT_SIZE, sp)
 	.set	at
 	ld	t1, PT_EPC(sp)		# skip syscall on return
 
+	LONG_S	v0, TI_SYSCALL($28)     # Store syscall number
+
 	dsubu	t0, v0, __NR_O32_Linux	# check syscall number
 	sltiu	t0, t0, __NR_O32_Linux_syscalls
 	daddiu	t1, 4			# skip to next instruction
```

Thanks

**Comment by xry111** [comment] 2024-03-28 12:00
> Hi @xry111,
> 
> Do you fancy to test following kernel patch? (based on linux-next)
> 
> ```
> diff --git a/arch/mips/kernel/asm-offsets.c b/arch/mips/kernel/asm-offsets.c
> index d1b11f66f748..cb1045ebab06 100644
> --- a/arch/mips/kernel/asm-offsets.c
> +++ b/arch/mips/kernel/asm-offsets.c
> @@ -101,6 +101,7 @@ void output_thread_info_defines(void)
>  	OFFSET(TI_CPU, thread_info, cpu);
>  	OFFSET(TI_PRE_COUNT, thread_info, preempt_count);
>  	OFFSET(TI_REGS, thread_info, regs);
> +	OFFSET(TI_SYSCALL, thread_info, syscall);
>  	DEFINE(_THREAD_SIZE, THREAD_SIZE);
>  	DEFINE(_THREAD_MASK, THREAD_MASK);
>  	DEFINE(_IRQ_STACK_SIZE, IRQ_STACK_SIZE);
> diff --git a/arch/mips/kernel/scall32-o32.S b/arch/mips/kernel/scall32-o32.S
> index 18dc9b345056..66b06b73664d 100644
> --- a/arch/mips/kernel/scall32-o32.S
> +++ b/arch/mips/kernel/scall32-o32.S
> @@ -77,6 +77,8 @@ loads_done:
>  	PTR_WD	load_a7, bad_stack_a7
>  	.previous
>  
> +	LONG_S	v0, TI_SYSCALL($28)     # Store syscall number
> +
>  	lw	t0, TI_FLAGS($28)	# syscall tracing enabled?
>  	li	t1, _TIF_WORK_SYSCALL_ENTRY
>  	and	t0, t1
> diff --git a/arch/mips/kernel/scall64-n32.S b/arch/mips/kernel/scall64-n32.S
> index 97456b2ca7dc..f20cb1f01f54 100644
> --- a/arch/mips/kernel/scall64-n32.S
> +++ b/arch/mips/kernel/scall64-n32.S
> @@ -44,6 +44,8 @@ NESTED(handle_sysn32, PT_SIZE, sp)
>  
>  	sd	a3, PT_R26(sp)		# save a3 for syscall restarting
>  
> +	LONG_S	v0, TI_SYSCALL($28)     # Store syscall number
> +
>  	li	t1, _TIF_WORK_SYSCALL_ENTRY
>  	LONG_L	t0, TI_FLAGS($28)	# syscall tracing enabled?
>  	and	t0, t1, t0
> diff --git a/arch/mips/kernel/scall64-n64.S b/arch/mips/kernel/scall64-n64.S
> index e6264aa62e45..3c1d708d5c09 100644
> --- a/arch/mips/kernel/scall64-n64.S
> +++ b/arch/mips/kernel/scall64-n64.S
> @@ -46,6 +46,8 @@ NESTED(handle_sys64, PT_SIZE, sp)
>  
>  	sd	a3, PT_R26(sp)		# save a3 for syscall restarting
>  
> +	LONG_S	v0, TI_SYSCALL($28)     # Store syscall number
> +
>  	li	t1, _TIF_WORK_SYSCALL_ENTRY
>  	LONG_L	t0, TI_FLAGS($28)	# syscall tracing enabled?
>  	and	t0, t1, t0
> diff --git a/arch/mips/kernel/scall64-o32.S b/arch/mips/kernel/scall64-o32.S
> index d3c2616cba22..900f2f45ff7b 100644
> --- a/arch/mips/kernel/scall64-o32.S
> +++ b/arch/mips/kernel/scall64-o32.S
> @@ -33,6 +33,8 @@ NESTED(handle_sys, PT_SIZE, sp)
>  	.set	at
>  	ld	t1, PT_EPC(sp)		# skip syscall on return
>  
> +	LONG_S	v0, TI_SYSCALL($28)     # Store syscall number
> +
>  	dsubu	t0, v0, __NR_O32_Linux	# check syscall number
>  	sltiu	t0, t0, __NR_O32_Linux_syscalls
>  	daddiu	t1, 4			# skip to next instruction
> ```
> 
> Thanks

Works for me!

FWIW I've misdiagnosed the "7" in the previous comment.  It's actually nfds but __NR_poll happens to be 7...

**Comment by FlyGoat** [comment] 2024-03-29 19:20
@zeha Thanks for reporting, will ask for stable backport after getting this merged.

**Comment by zeha** [comment] 2024-03-30 00:19
I've opened #2887 for a similar problem on armel.

**Comment by masatake** [comment] 2024-04-04 18:47
I will add code to skip the test case as I did in #2822 and #2888.

**Comment by masatake** [comment] 2024-04-04 19:09
Could you try #2910 ?

**Comment by xry111** [comment] 2024-04-06 09:46
> Could you try #2910 ?

I've patched the kernel and I don't want to remove the patch now, but I just eyeballed #2910 and it should be able to skip the test with unpatched kernel.

**Comment by zeha** [comment] 2024-04-08 15:23
#2910 skips it:
```
         lsfd: XMODE.m for classical system calls for multiplexing ...
                : pselect6                    ... SKIPPED (incorrect syscall number in /proc/70370/syscall)
                : select                      ... SKIPPED (the multiplexer select is not available)
                : poll                        ... SKIPPED (incorrect syscall number in /proc/70384/syscall)
                : ppoll                       ... SKIPPED (incorrect syscall number in /proc/70394/syscall)
           ... OK (all 4 sub-tests PASSED)
```

Thanks!

**Comment by masatake** [comment] 2024-04-08 17:08
@karelzak We can close this. I wonder why merging #2910 doesn't close this automatically.

**Closed** 2024-04-09 10:16 UTC
