### ISSUE TITLE
script: run /usr/bin/script command causes the user login information to be lost

### ISSUE THREAD

**Issue by zhangyao108** [util-linux/util-linux#1904] opened 2022-11-14 02:27 UTC
![image](https://user-images.githubusercontent.com/110269838/201562019-982989d5-ac5f-45e7-9eb8-5312dd44637c.png)
`w`
`who am i`
`script`
`w`
`who am i`
No printing at all

**Comment by karelzak** [comment] 2022-11-14 12:22
It should have been implemented since f0bc3fa0cf45f484ea696ef063a10b65d1a45e13, but I'm not sure if it works in all cases.

Do you have util-linux compiled with --with-utempter?

**Comment by zhangyao108** [comment] 2022-11-14 13:48
I recompiled with --with-utempter.
![image](https://user-images.githubusercontent.com/110269838/201670911-2f2371c9-4162-4409-abdf-1af0e730aab9.png)
[https://github.com/util-linux/util-linux/commit/b1154c4ece2192345efe1a3fb835ae28c8f92154](https://gitee.com/link?target=https%3A%2F%2Fgithub.com%2Futil-linux%2Futil-linux%2Fcommit%2Fb1154c4ece2192345efe1a3fb835ae28c8f92154)
Revert script.c modify, it worked!
![image](https://user-images.githubusercontent.com/110269838/201676397-1b8eddb3-85da-435b-987e-2aaead5622bd.png)

**Comment by karelzak** [comment] 2022-11-15 14:04
Ah, good catch. utempter calls suid wrapper, so it needs to fork and play with SIGCHLD.

The problem is that after ul_pty_setup() SIGCHLD is controlled by script, but call tempter_add_record(ul_pty_get_childfd(ctl.pty), NULL) before ul_pty_setup() does not make sense because `master` FD is not initialized yet (the current situation).

The possible solution is to split ul_pty_setup() into two functions; first, initialize master and space FDs, and second, initialize signalfd() -- then we can tempter_add_record() between these two functions.

**Comment by karelzak** [comment] 2022-11-16 08:23
Fixed now. 

Thanks for your report and debugging!

**Closed** 2022-11-16 08:22 UTC
