### ISSUE TITLE
mount -a fails to use UUID if /proc and /sys are to be mounted

### ISSUE THREAD

**Issue by stsp** [util-linux/util-linux#1492] opened 2021-11-04 15:36 UTC
I am using buildroot with mount from util-linux-2.37.2, libmount 2.37.2.
When my fstab contains UUIDs,
mount at boot fails to find them.
After some experimenting, it seems
that it would need /proc or /sys to
find device by UUID. And the fact
is, that exact "mount -a" at boot is
used to mount /proc and /sys.
So if they were already mounted,
then UUID look-up succeeds. If
they are to be mounted by the
same "mount -a", then UUID fails.

I don't think I've seen this problem
on earlier versions. I suspect
"mount -a" should delay the UUID/LABEL
mounts to the last step, so that
/proc and /sys are always mounted
first.

**Comment by karelzak** [comment] 2021-11-16 09:49
> And the fact is, that exact "mount -a" at boot is used to mount /proc and /sys."

I don't think so. If I remember classic init scripts then /proc and /sys are always mounted by separate mount(8) calls before `mount -a`.

The libmount uses libblkid to evaluate the tags (UUID= or LABEL=). The libblkid uses udevd symlinks in /dev/disk/by-* and if not available then it reads /sys to get a list of block devices to scan for the tags. The old versions (before v2.37) use /proc/partitions rather than /sys. Anyway, this dependence on /proc is there for more than 15 years ...

`mount -a` also uses /proc/self/mountinfo to ignore already mounted filesystems.

Please, use 
```
  mount -t proc proc /proc
  mount -t sysfs sysfs /sys
```
in your scripts before mount -a. Note that /proc and /sys are often already mounted in initrd.

I don't see any elegant way how to improve it. It would be possible to scan all /dev and try all block devices, but it does not make sense if the kernel provides /sys with all the information.

And postpone UUID= until you get /proc and /sys is against `mount -a` semantic as it always follows fstab order.

**Comment by karelzak** [comment] 2021-11-16 09:50
Closing, not a bug.

**Comment by stsp** [comment] 2021-11-16 10:11
OK, thanks for you time.
I'll report that to buildroot then.

**Comment by stsp** [comment] 2021-11-16 12:47
> And postpone UUID= until you get /proc and /sys is against mount -a semantic as it always follows fstab order.

Hmm, then we actually have
a bug here. The fstab in question:
```
# <file system> <mount pt>      <type>  <options>       <dump>  <pass>
/dev/root       /               ext2    rw,noauto       0       1
proc            /proc           proc    defaults        0       0
devpts          /dev/pts        devpts  defaults,gid=5,mode=620,ptmxmode=0666
0       0
tmpfs           /dev/shm        tmpfs   mode=0777       0       0
tmpfs           /tmp            tmpfs   mode=1777       0       0
tmpfs           /run            tmpfs   mode=0755,nosuid,nodev  0       0
sysfs           /sys            sysfs   defaults        0       0
UUID="8f1b147f-2756-4d08-bd92-217fff11b182" /mnt/drive_c ext4 rw,nodev,nosuid,no
exec,noatime 0 0
```

As you can see, /sys is mounted
BEFORE UUID.
And yet that doesn't work.
So should this be re-opened?

**Comment by stsp** [comment] 2021-11-16 12:49
So to be clear:
even if you have /proc and /sys
in fstab before UUID usage, you
still can't use "mount -a" alone.
So why is that?

**Comment by karelzak** [comment] 2021-11-16 13:15
> So to be clear: even if you have /proc and /sys in fstab before UUID usage, you still can't use "mount -a" alone. So why is that?

That's a good question. I need to test it with "LIBMOUNT_DEBUG=all LIBBLKID_DEBUG=all mount --all".

**Comment by karelzak** [comment] 2021-11-16 13:26
I guess (not tested yet) the problem is 
```C
       /* ignore already mounted filesystems */
        rc = mnt_context_is_fs_mounted(cxt, *fs, &mounted);
        if (rc) 
            return rc;
```
in libmount/src/context_mount.c:mnt_context_next_mount(). There we need to care about situations related to missing /proc or /sys and ignore 'rc' in this case.

**Comment by stsp** [comment] 2021-11-16 13:34
I can test the patch if you want.

**Comment by karelzak** [comment] 2021-11-18 13:41
The problem should be fixed in the git "master" branch. I have tested it in chroot it works for me ;-)

**Comment by karelzak** [comment] 2021-11-18 14:39
Well, if /proc is not mounted then the mount table is empty (in libmount).

Can you try `"LIBMOUNT_DEBUG=all LIBBLKID_DEBUG=all mount --all` for your use-case?

**Comment by karelzak** [comment] 2021-11-18 14:43
... and it would be better to try the current git, not only the patch.

**Comment by stsp** [comment] 2021-11-18 14:45
But /proc IS mounted, because,
as I said, buildroot mounts /proc
and /dev before anything else.
The problem is ONLY unmounted
sysfs.
So should I still do the aforementioned
logging?

**Comment by karelzak** [comment] 2021-11-19 12:26
I probably see where is the issue. There is a cache in libblkid and it does not re-read the cache.

**Comment by stsp** [comment] 2021-11-20 11:16
Sorry, github only posted the comment
via email, but not the fact that the patch
is here, so I didn't know.

Now I tested it and it works, thank you!

> The library checks the delay between probes, and if the delay is
> too short, it does not read devices.

OMG, nothing is deterministic
these days...

**Comment by karelzak** [comment] 2021-11-22 08:56
Thanks for your report, test, and patience! ;-)  It's will be fixed in the next release.

**Closed by karelzak** 2021-11-22 08:56 UTC
Labels: NOTABUG

**Comment by stsp** [comment] 2021-11-22 09:49
Good to know, thanks. :)
Note that buildroot already took
your patch, so if by "will be fixed
in the next release" you mean
something else than what is
in the current patch, then
please speak up.
