### ISSUE TITLE
`disk-utils/raw.8` missing from util-linux-2.37.3 release tarball

### ISSUE THREAD

**Issue by xry111** [util-linux/util-linux#1579] opened 2022-01-24 18:59 UTC
The tarball (https://www.kernel.org/pub/linux/utils/util-linux/v2.37/util-linux-2.37.3.tar.xz) does not contain this file.

It causes FTBFS when `asciidoctor` is not installed:

```
make  all-recursive
make[1]: Entering directory '/home/xry111/sources/util-linux-2.37.3'
Making all in po
make[2]: Entering directory '/home/xry111/sources/util-linux-2.37.3/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/xry111/sources/util-linux-2.37.3/po'
make[2]: Entering directory '/home/xry111/sources/util-linux-2.37.3'
make[2]: *** No rule to make target 'disk-utils/raw.8', needed by 'all-am'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/xry111/sources/util-linux-2.37.3'
make[1]: *** [Makefile:14611: all-recursive] Error 1
make[1]: Leaving directory '/home/xry111/sources/util-linux-2.37.3'
make: *** [Makefile:6321: all] Error 2
```

**Comment by karelzak** [comment] 2022-01-25 07:59
Install asciidoctor or use --disable-raw

The reason is that the tarball has been generated on the system without raw support, so pre-generated man pages do not include raw.8. Note that raw is not supported by recent kernels and it is a deprecated tool.

**Comment by karelzak** [comment] 2022-01-25 09:52
Note, this is a duplicate of https://github.com/util-linux/util-linux/issues/1577. Let's continue in discussion there. Thanks.

**Closed by karelzak** 2022-01-25 09:52 UTC
