### ISSUE TITLE
[tests] fdisk/bsd fails on ppc64le

### ISSUE THREAD

**Issue by zeha** [util-linux/util-linux#1655] opened 2022-04-13 11:05 UTC
Hi,

as noted in #1392 the expected test data for ppc64le was not updated in #1386.
Full build log on Debian buildds is here: https://buildd.debian.org/status/fetch.php?pkg=util-linux&arch=ppc64el&ver=2.38-2&stamp=1649798385&raw=0

I think there is something else going on in that diff too, so I do not want to blindly send an MR changing the expected output:

```diff
================= O/E diff ===================
--- /<<PKGBUILDDIR>>/tests/output/fdisk/bsd	2022-04-12 21:18:15.555731451 +0000
+++ /<<PKGBUILDDIR>>/tests/expected/fdisk/bsd_0_64.LE	2022-01-06 13:52:17.967125171 +0000
@@ -47,16 +47,16 @@
 Disklabel type: dos
 Disk identifier: <removed>
 
-Device     Boot Start   End Sectors Id Type  Start-C/H/S End-C/H/S Attrs
-<removed>1       2048  4095    2048 83 Linux     0/32/33    0/65/1 
+Device     Boot Start   End Sectors Size Id Type
+<removed>1       2048  4095    2048   1M 83 Linux
 -------------------
 
 Create 2nd primary partition
 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 *
 000001b0  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 20  |............... |
-000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 41  |!..A...........A|
-000001d0  02 00 83 46 05 01 00 10  00 00 00 40 00 00 00 00  |...F.......@....|
+000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 04  |!..A............|
+000001d0  01 3e 83 13 41 36 00 10  00 00 00 40 00 00 00 00  |.>..A6.....@....|
 000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
 00000200  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
@@ -66,8 +66,8 @@
 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 *
 000001b0  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 20  |............... |
-000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 41  |!..A...........A|
-000001d0  02 00 a5 46 05 01 00 10  00 00 00 40 00 00 00 00  |...F.......@....|
+000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 04  |!..A............|
+000001d0  01 3e a5 13 41 36 00 10  00 00 00 40 00 00 00 00  |.>..A6.....@....|
 000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
 00000200  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
@@ -82,17 +82,17 @@
 Disklabel type: dos
 Disk identifier: <removed>
 
-Device     Boot Start   End Sectors Id Type    Start-C/H/S End-C/H/S Attrs
-<removed>1       2048  4095    2048 83 Linux       0/32/33    0/65/1 
-<removed>2       4096 20479   16384 a5 FreeBSD      0/65/2    1/70/5 
+Device     Boot Start   End Sectors Size Id Type
+<removed>1       2048  4095    2048   1M 83 Linux
+<removed>2       4096 20479   16384   8M a5 FreeBSD
 -------------------
 
 Create default BSD
 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 *
 000001b0  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 20  |............... |
-000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 41  |!..A...........A|
-000001d0  02 00 a5 46 05 01 00 10  00 00 00 40 00 00 00 00  |...F.......@....|
+000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 04  |!..A............|
+000001d0  01 3e a5 13 41 36 00 10  00 00 00 40 00 00 00 00  |.>..A6.....@....|
 000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
 00000200  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
@@ -144,8 +144,8 @@
 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 *
 000001b0  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 20  |............... |
-000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 41  |!..A...........A|
-000001d0  02 00 a5 46 05 01 00 10  00 00 00 40 00 00 00 00  |...F.......@....|
+000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 04  |!..A............|
+000001d0  01 3e a5 13 41 36 00 10  00 00 00 40 00 00 00 00  |.>..A6.....@....|
 000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
 00000200  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

Sorry for not catching this in 2.38-rcX, with the lsfd and hardlink test issues I forgot to look at ppc64le in detail.

/cc @pali

**Comment by zeha** [comment] 2022-04-13 11:08
Ah the diff in the hexdump is "caused" by #1385 (so - expected)?

**Comment by pali** [comment] 2022-04-15 09:28
> ```diff
> -Device     Boot Start   End Sectors Id Type  Start-C/H/S End-C/H/S Attrs
> -<removed>1       2048  4095    2048 83 Linux     0/32/33    0/65/1 
> +Device     Boot Start   End Sectors Size Id Type
> +<removed>1       2048  4095    2048   1M 83 Linux
> ```

This is caused by PR https://github.com/util-linux/util-linux/pull/1386 which added code to print also C/H/S numbers in tests. So human readable part of expected output needs to be updated. This allowed me to diagnostic what is wrong in tests.

> Ah the diff in the hexdump is "caused" by #1385 (so - expected)?

And different C/H/S numbers in hex-part of expected output were wrong and were fixed by PR https://github.com/util-linux/util-linux/pull/1385. Seems that github does not run all tests and I have updated/fixed expected tests output only for cases which were failing on my machine and on github.

If you have machine on which tests are failing, it would be nice if you can look at it and fix it.

**Comment by zeha** [comment] 2022-04-15 09:46
> If you have machine on which tests are failing, it would be nice if you can look at it and fix it.

please check #1656

**Closed** 2022-04-19 09:43 UTC
