### ISSUE TITLE
fdisk broken on sparc with >=2.24

### ISSUE THREAD

**Issue by stintel** [util-linux/util-linux#207] opened 2015-07-03 22:50 UTC
Works fine in 2.23.2, I suspect something went wrong with the fdisk refactoring in util-linux 2.24. Also tested 2.25.2 and 2.26.2, they have the same problem.

Steps to reproduce:
1. fdisk /dev/sda
2. s
3. p
4. n

Actual Results:  
livecd ~ # fdisk /dev/sda

Welcome to fdisk (util-linux 2.24.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Command (m for help): s
Created a new partition 1 of type 'Linux native' and of size 512 B.
Created a new partition 2 of type 'Linux swap' and of size 512 B.
Created a new partition 3 of type 'Whole disk' and of size 512 B.
Created a new Sun disklabel.

Command (m for help): p
Disk /dev/sda: 68.4 GiB, 73407865856 bytes, 143374738 sectors
Geometry: 255 heads, 270582939648 sectors/track, 0 cylinders
Units: sectors of 1 \* 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: sun

Command (m for help): n
Incomplete geometry setting.

Expected Results:  
livecd util-linux # fdisk /dev/sda
Welcome to fdisk (util-linux 2.23.2).

Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Command (m for help): s
Building a new Sun disklabel.
Partition 1 of type Linux native and of size 68.3 GiB is set
Partition 2 of type Linux swap and of size 47.1 MiB is set
Partition 3 of type Whole disk and of size 68.4 GiB is set

Command (m for help): p

Disk /dev/sda (Sun disk label): 255 heads, 63 sectors, 8924 cylinders
Units = sectors of 1 \* 512 bytes

   Device Flag    Start       End    Blocks   Id  System
/dev/sda1             0 143267670  71633835   83  Linux native
/dev/sda2  u  143267670 143364060     48195   82  Linux swap
/dev/sda3             0 143364060  71682030    5  Whole disk

Command (m for help): n
Partition number (4-8, default 4):

**Comment by avollmerhaus** [comment] 2016-06-04 10:24
I ran into this, too. Will this ever get fixed?

**Comment by karelzak** [comment] 2016-06-06 13:03
I'm not able to reproduce the problem with v2.28, anyway:

 > Geometry: 255 heads, 270582939648 sectors/track, 0 cylinders

seems very strange. Maybe  "LIBFDISK_DEBUG=all fdisk <disk>" will provide more information.

**Comment by avollmerhaus** [comment] 2016-06-30 13:13
I tried to reproduce with 2.26.2 on amd64 (tried to create a sun disklabel on an LVM LV), worked perfectly. I'll try on sparc as soon as I have access to the hardware again.
Unfortunately all live cds for sparc64 are somewhat outdated, I tried with the gentoo live cd from 2014

**Comment by DerDakon** [comment] 2017-03-15 12:33
You can find me in #gentoo-sparc on Freenode if you have anything to test. Here is the log:

33421: libfdisk:     INIT: library debug mask: 0xffff
Available "LIBFDISK_DEBUG=<name>[,...]|<mask>" debug masks:
   all      [0xffff] : info about all subsystems
   ask      [0x0010] : fdisk dialogs
   help     [0x0001] : this help
   cxt      [0x0004] : library context (handler)
   label    [0x0008] : disk label utils
   part     [0x0040] : partition utils
   parttype [0x0080] : partition type utils
   script   [0x0200] : sfdisk-like scripts
   tab      [0x0100] : table utils
33421: libfdisk:      CXT: [0x38870]: alloc
33421: libfdisk:      ASK: [0x3b630]: alloc
33421: libfdisk:      ASK: [0x3b630]: do_ask for 'info'

Welcome to fdisk (util-linux 2.28.2).
33421: libfdisk:      ASK: [0x3b630]: do_ask done [rc=0]
33421: libfdisk:      ASK: [0x3b630]: reset
33421: libfdisk:      ASK: [0x3b630]: free
33421: libfdisk:      ASK: [0x3b630]: alloc
33421: libfdisk:      ASK: [0x3b630]: do_ask for 'info'
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

33421: libfdisk:      ASK: [0x3b630]: do_ask done [rc=0]
33421: libfdisk:      ASK: [0x3b630]: reset
33421: libfdisk:      ASK: [0x3b630]: free
33421: libfdisk:      CXT: [0x38870]: assigning device /dev/sdb
33421: libfdisk:      CXT: [0x38870]: *** resetting context
33421: libfdisk:      CXT: [0x38870]: /dev/sdb: discovering topology...
33421: libfdisk:      CXT: [0x38870]: initialize libblkid prober
33421: libfdisk:      CXT: [0x38870]: result: log/phy sector size: 512/512
33421: libfdisk:      CXT: [0x38870]: result: fdisk/optimal/minimal io: 512/0/512
33421: libfdisk:      CXT: [0x38870]: /dev/sdb: discovering geometry...
33421: libfdisk:      CXT: [0x38870]: total sectors: 1953525168 (ioctl=1953525168)
33421: libfdisk:      CXT: [0x38870]: result: C/H/S: 0/255/0
33421: libfdisk:      CXT: [0x38870]: initialize in-memory first sector buffer [sector_size=512]
33421: libfdisk:      CXT: [0x38870]: reading: offset=0, size=512
33421: libfdisk:      CXT: [0x38870]: probing for gpt
33421: libfdisk:    LABEL: GPT probe failed
33421: libfdisk:      CXT: [0x38870]: probing for dos
33421: libfdisk:      CXT: [0x38870]: probing for bsd
33421: libfdisk:    LABEL: not found magic
33421: libfdisk:      CXT: [0x38870]: probing for sgi
33421: libfdisk:      CXT: [0x38870]: probing for sun
33421: libfdisk:      CXT: [0x38870]: no label found
33421: libfdisk:      CXT: [0x38870]: appling user device properties
33421: libfdisk:      CXT: [0x38870]: reseting alignment...
33421: libfdisk:      CXT: [0x38870]: alignment reseted to: first LBA=2048, last LBA=1953525167, grain=1048576 [rc=0]
33421: libfdisk:      CXT: [0x38870]: new C/H/S: 0/255/0
33421: libfdisk:      CXT: [0x38870]: new log/phy sector size: 512/512
33421: libfdisk:      CXT: [0x38870]: wipe check: initialize libblkid prober
33421: libfdisk:      CXT: [0x38870]: initialized for /dev/sdb [READ-WRITE]
33421: libfdisk:      ASK: [0x3b8a0]: alloc
33421: libfdisk:      ASK: [0x3b8a0]: do_ask for 'info'
Device does not contain a recognized partition table.
33421: libfdisk:      ASK: [0x3b8a0]: do_ask done [rc=0]
33421: libfdisk:      ASK: [0x3b8a0]: reset
33421: libfdisk:      ASK: [0x3b8a0]: free
33421: libfdisk:      CXT: [0x38870]: --> switching context to sun!
33421: libfdisk:      CXT: [0x38870]: create a new sun label
33421: libfdisk:      CXT: [0x38870]: zeroize in-memory first sector buffer
33421: libfdisk:      ASK: [0x3b8f0]: alloc
33421: libfdisk:      ASK: [0x3b8f0]: do_ask for 'info'
Created a new partition 1 of type 'Linux native' and of size 512 B.
33421: libfdisk:      ASK: [0x3b8f0]: do_ask done [rc=0]
33421: libfdisk:      ASK: [0x3b8f0]: reset
33421: libfdisk:      ASK: [0x3b8f0]: free
33421: libfdisk:      ASK: [0x3b8f0]: alloc
33421: libfdisk:      ASK: [0x3b8f0]: do_ask for 'info'
Created a new partition 2 of type 'Linux swap' and of size 512 B.
33421: libfdisk:      ASK: [0x3b8f0]: do_ask done [rc=0]
33421: libfdisk:      ASK: [0x3b8f0]: reset
33421: libfdisk:      ASK: [0x3b8f0]: free
33421: libfdisk:      ASK: [0x3b8f0]: alloc
33421: libfdisk:      ASK: [0x3b8f0]: do_ask for 'info'
Created a new partition 3 of type 'Whole disk' and of size 512 B.
33421: libfdisk:      ASK: [0x3b8f0]: do_ask done [rc=0]
33421: libfdisk:      ASK: [0x3b8f0]: reset
33421: libfdisk:      ASK: [0x3b8f0]: free
33421: libfdisk:      ASK: [0x3b860]: alloc
33421: libfdisk:      ASK: [0x3b860]: do_ask for 'info'
Created a new Sun disklabel.
33421: libfdisk:      ASK: [0x3b860]: do_ask done [rc=0]
33421: libfdisk:      ASK: [0x3b860]: reset
33421: libfdisk:      ASK: [0x3b860]: free

Command (m for help): n
33421: libfdisk:      ASK: [0x50d50]: alloc
33421: libfdisk:      ASK: [0x50d50]: do_ask for 'warnx'
Incomplete geometry setting.
33421: libfdisk:      ASK: [0x50d50]: do_ask done [rc=0]
33421: libfdisk:      ASK: [0x50d50]: reset
33421: libfdisk:      ASK: [0x50d50]: free

**Comment by karelzak** [comment] 2017-03-15 15:42
I did some changes to the libfdisk geometry code, can you try it with the current git tree?

```
git clone git://git.kernel.org/pub/scm/utils/util-linux/util-linux.git
cd util-linux
./autogen.sh
./configure
make fdisk
```

**Comment by DerDakon** [comment] 2017-03-15 16:13
Got one compiler warning.

libfdisk/src/gpt.c: In function 'gpt_read_entries':
libfdisk/src/gpt.c:833:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

Partitioning seems to work so far.

**Comment by mator** [comment] 2021-11-02 09:49
@karelzak what needs to be done with this issue? i could check it on sparc64 hardware/VM

**Comment by karelzak** [comment] 2021-11-02 11:12
> @karelzak what needs to be done with this issue? i could check it on sparc64 hardware/VM

You can try to reproduce the original issue as reported in the first comment.

It seems the issue is 
```
     rc = (fdisk_label_require_geometry(cxt->label) &&
                    (!cxt->geom.heads || !cxt->geom.sectors  || !cxt->geom.cylinders));
```
but it seems system does not provide all geometry, from debug log:
```
   33421: libfdisk: CXT: [0x38870]: result: C/H/S: 0/255/0
```
The current version uses some fallback solutions, so I guess it's better now, but ....

**Comment by karelzak** [comment] 2021-11-23 10:03
Closing. Please, reopen if see that the issue remains. Thanks!

**Closed by karelzak** 2021-11-23 10:03 UTC
